### ISSUE TITLE
Disabling triggers using a custom setting

### ISSUE THREAD

**Issue by mustafaturabali** [apex-enterprise-patterns/fflib-apex-common#126]
Hello @afawcett,

Hope you are well. So, I have a project where I need to give client salesforce.com admin control to enable/disable triggers by using a custom setting. For e.g. there are triggers on Account, Opportunity and Contact. I want to give Administrator to enable disable triggers using a custom setting with fields like these:
1. Disable All Triggers (disables all apex triggers across the org)
2. Disable Opportunity Trigger (disables all Opportunity triggers)
3. Disable Opportunity Creat Invoices (disables a particular method in Opportunities SObjectDomain class)... and so on for Account and Contact objects.

Can you please advise on where should I keep the additional logic for disabling all triggers, particular object trigger disabling, and also if possible how to control a particular method (functionality) of a trigger? Ideally, I don't want to make changes in fflib_SObjectDomain class for keeping it upgradable from this project.

Let me know what you think would be the best way to do it.

Thanks,
Mustafa

**Comment by Autobat** [comment]
Hey @mustafaturabali 

I would check out:

 https://andyinthecloud.com/2016/04/13/disabling-trigger-events-in-apex-enterprise-patterns/

The pattern you are looking for is already within fflib and exposed as a fluent api.  You can programmatically turn off the execution of any trigger event.

Let me know how you get on or if you need any help,

Cheers,

Chris

**Comment by mustafaturabali** [comment]
Hello Chris,

This is what I have done so far:

public static TriggerEvent getTriggerEvent(Type domainClass) {
		if (!TriggerEventByClass.containsKey(domainClass)) {
			TriggerEvent objTriggerEvent = new TriggerEvent();
			if(EJ_Settings__c.getOrgDefaults().Disable_All_Triggers__c) {
				objTriggerEvent.disableAll();
			}
			TriggerEventByClass.put(domainClass, objTriggerEvent);
		}

		return TriggerEventByClass.get(domainClass);
	}

I have modified this method in fflib_SObjectDomain class to disable all events for any trigger being called using custom settings field.

Let me know if you have a better solution in mind.

Regards,
Mustafa

**Comment by Autobat** [comment]
Hey Mustafa,

Sorry for the delay, i have been offline with the flu.

That looks ok.  It would allow a developer to reenable the triggers programmatically as this only gets set on the first invocation - this might be beneficial depending on your use case.

**Comment by afawcett** [comment]
Its a shame @mustafaturabali had to modify the code to achieve this. As this will impact future upgrading of this library. Any thoughts on how to avoid this?

**Comment by Autobat** [comment]
It would be possible if we created some core fflib custom settings.

Would this be something the library wanted?  It would be something quite simple.

Let me think about it and propose a solution to the group.

Chris Mail
Director
+61 424 022 071

**Comment by mustafaturabali** [comment]
Hello,

Just to add my two cents.. May be we can provide an interface/virtual method like isEnabled() and leave the implementing class to handle it? This will let developers provide their own implementation of how they wanna handle it i.e. using custom settings or some criteria based enabling/disabling of certain triggers. 

Mustafa

**Comment by dudunato** [comment]
Any pull request for that?

**Comment by afawcett** [comment]
@mustafaturabali "May be we can provide an interface/virtual method like isEnabled() and leave the implementing class to handle it?" is that not what is already provided per what @Autobat was saying above?

**Comment by gsinha-atrium** [comment]
Hey @afawcett @Autobat , 

Have we enabled any feature update to this? I am thinking of custom metadata to have granular control over the functionality. In the fflibDomain, we can have the defined custom metadata and use the map associate to enable and disable the feature [
[Trigger Control By Metadata.pdf](https://github.com/apex-enterprise-patterns/fflib-apex-common/files/5864834/Trigger.Controlel.By.Metadata.pdf)
](url)

**Comment by pantherschools** [comment]
@afawcett @Autobat 

Did we upgrade the library to use the Custom Metadata or Custom Settings to Control the Trigger Events instead of writing them in apex code?

**Comment by ImJohnMDaniel** [comment]
@pantherschools, have you checked out the [AT4DX library](https://github.com/apex-enterprise-patterns/at4dx) which is deployed alongside the FFLIB Apex Common library?  It controls domain processes via a custom metadata approach -- see [Domain Process Injection](https://youtu.be/yw-QoE4l0p0?t=999)

**Comment by pantherschools** [comment]
@ImJohnMDaniel I did deploy the FFLIB code yesterday only and I do not see any custom metadata deployed to my org.

**Comment by ImJohnMDaniel** [comment]
The enablement of domain process injection via Custom Metadata comes with the addition of the AT4DX framework.

**Comment by wimvelzeboer** [comment]
@pantherschools The AT4DX framework offers a great set of features, but if you find that too much there is also a lightweight alternative offered by the [fflib-apex-extensions](https://github.com/wimvelzeboer/fflib-apex-extensions). Please review the wiki pages on that link which will explain how to use it.

**Comment by daveespo** [comment]
The topic of preventing trigger re-entrancy and disabling triggers has come up many times over the years. There are a million different 'solutions' that people have built to address different scenarios. We have no plans to introduce a solution into this library given the different use cases and lack of a one-size-fits-all solution.
