### ISSUE TITLE
fflib_SObjectSelector.cls - Accessing fflib_QueryFactor.SortOrder

### ISSUE THREAD

**Issue by tmowbrey** [apex-enterprise-patterns/fflib-apex-common#13]
When compiling fflib_SObjectSelector, I am receiving a compile error stating that fflib_QueryFactory.SortOrder does not exist (line 348 - QueryFactory.SortOrder fieldSortOrder = QueryFactory.SortOrder.ASCENDING;). Any idea why that might be happening?

**Comment by mustafaturabali** [comment]
HI.. in case if there is still someone struggling with this, I would like to share what is probably wrong with the code. If you are like me who removed the fflib_ prefix using find/replace, you must not have noticed that QueryFactory instance being passed into parameters is also named queryFactory. In this case, the compiler is looking at the instance variable to find a variable named SortOrder and not enum. 

I made this same mistake of removing the fflib_ prefix.. better get it back :). @afawcett Thanks a lot for this wonderful library.

**Comment by afawcett** [comment]
Your very welcome @mustafaturabali, but its not just me, there are now many contributors! 👍

**Comment by tjsully** [comment]
@mustafaturabali Thank you!!  I had removed the prefix as well and I was getting the same error.
