### ISSUE TITLE
IDGenerator fails with History Objects

### ISSUE THREAD

**Issue by itsmebasti** [apex-enterprise-patterns/fflib-apex-common#155]
`fflib_IDGenerator.generate(CaseHistory.SObjectType)`
results in :

> System.StringException: Invalid id: null000000000001
Class.UP2GO_2T.fflib_IDGenerator.generate: line 41, column 1

Same for Custom__History objects.

**Comment by afawcett** [comment]
Bah.... not really sure what we can do about this tbh, feels like a platform issue. @capeterson any thoughts?

**Comment by cropredyHelix** [comment]
the bigger issue is that xxxHistory objects can't be mocked, even using json.deserialize technique

**Comment by daveespo** [comment]
This is a duplicate of an issue over in the Mocks repo so I'm closing this one since it doesn't belong here

https://github.com/apex-enterprise-patterns/fflib-apex-mocks/issues/75
