### ISSUE TITLE
fflib_SObjectSelector getOrderBy sensitive to Platform Encryption rules

### ISSUE THREAD

**Issue by cropredyHelix** [apex-enterprise-patterns/fflib-apex-common#180]
In Shield Platform Encryption, you can't use Order By on an encrypted field.  This can't be detected at analysis time by Shield Platform Encryption if one is using the fflib_SObjectSelector and fflib_QueryFactory as these assemble SOQL dynamically.

Hence, this method in fflib_SObjectSelector will generate SOQL that, when executed, will throw a `System.QueryException: field 'Name' can not be sorted in a query call` if the Name field is the order by:

```
/**
* Override this method to control the default ordering of records returned by the base queries, 
* defaults to the name field of the object or CreatedDate if there is none
**/
public virtual String getOrderBy()
    {
        if(m_orderBy == null) {
   		m_orderBy = 'CreatedDate';
   		if(describeWrapper.getNameField() != null) {
	    		m_orderBy = describeWrapper.getNameField().getDescribe().getName();
	    	}
	}
   	return m_orderBy;
    }
```

Suggestions:

1.  If not overridden by selector class, don't default to the Name field if the Name field describe has `isSortable()=false`
2. If overridden by selector class, throw exception if fflib_QueryFactory.Ordering's field is not sortable. See method `addOrdering`.

Platform Encryption on the Name field (e.g. `Contact.Name`) means the application can't use the database to sort on this field. fflib should not generate SOQL that won't execute.

**Comment by afawcett** [comment]
@cropredyHelix sounds like a good idea to me! @dfruddffdc assuming you agree, perhaps at least mark this as an enhancement for now?

**Comment by afawcett** [comment]
@agarciaffdc can you mark this for now as an enhancement. Thank you. 👍

**Comment by wimvelzeboer** [comment]
@cropredyHelix @afawcett I think we can close this issue as this is implemented, right?

**Comment by cropredyHelix** [comment]
@wimvelzeboer - I can see that it was implemented by code inspection although I wonder why `.isSortable()` wasn't used rather than `.isEncrypted` - as a non-sortable field can't be in Order By - encryption is just a use case of a non-sortable field.

**Comment by daveespo** [comment]
This was brought up over on the commentary on PR #452  (i.e. should we use 'isSortable' instead of 'isEncrypted') but until there is a bug filed for a realistic use case where the current implementation is a bug, we are not going to make a speculative change.
