### ISSUE TITLE
Unable to set enforcement of CRUD while extending fflib_SObjectSelector 

### ISSUE THREAD

**Issue by fabianPas** [apex-enterprise-patterns/fflib-apex-common#187]
At the company I am employed at, we are developing a customer portal, the users that make use of the customer have a license not enabling us setting sharing rules on a lot of objects. We are working around that by using inner 'without sharing' classes and an extra constructor on the selector class, disabling CRUD.

```
public MF_OpportunitiesSelector(Boolean enforceCRUD)
{
	super(false, enforceCRUD, false);
	this.withSharing = enforceCRUD;
}
```

Using fflib, we currently don't have the opportunity to extend the `fflib_SObjectSelector` and override for example the member `m_enforceCRUD`.

Is there a reason the members `m_includeFieldSetFields`, `m_enforceFLS`, `m_enforceCRUD` are made private thus can't be overwritten by a class extending `fflib_SObjectSelector`? If there is no reason, would it be a problem to create a PR and make those members `protected`

Another solution could be implementing the `DomainFactory` custom constructor logic into the `SelectorFactory`.

**Comment by afawcett** [comment]
Can you explain why you cannot extend fflib_SObjectSelector?

**Comment by fabianPas** [comment]
@afawcett It is possible to extend fflib_SObjectSelector, but we can't override the members m_includeFieldSetFields, m_enforceFLS, m_enforceCRUD, so extending fflib_SObjectSelector is not a viable solution in this situation.

**Comment by afawcett** [comment]
@fabianPas these are settable via the constructor.
