### ISSUE TITLE
No build.properties-file? Where are credentials for ant deploy taken from

### ISSUE THREAD

**Issue by mssksg** [apex-enterprise-patterns/fflib-apex-common#207]
I was wondering why unlike in the Apex Mock there is no file `build.properties` which is then linked in `build.xml`.
Somehow for me clicking on the deploy to salesforce-button does not work, so I tried to deploy it with ant which worked for Apex Mock very well, but here I got an INVALID_LOGIN error all the time, until I realized that the build.xml is not taking the properties from the build.properties-file I copied into the directory...
Did I miss something how it was intended here to do `ant deploy` here?

**Comment by afawcett** [comment]
Yes this looks like an oversight. The Ant usage here is mainly for the CI integration with Travis. Though its reasonable to expect that you can use it manually. I would copy over the file from Apex Mock as a template. Meanwhile i think these repos should move to DX format now that it supports deployment to non-scratch orgs.

**Comment by afawcett** [comment]
Closing this as we are heading towards SFDX support for this repo.
