### ISSUE TITLE
Update api version classes

### ISSUE THREAD

**Issue by dieffrei** [apex-enterprise-patterns/fflib-apex-common#215]
There some objets are not visible for fflib classes since the api version is out updated.
There are some standard objects like ServiceAppointment the QueryFactory doesn't work correctly and throw and error like: ServiceAppointment access is denied.
This error was really hard to figured out, then I think could be good update the api version of the classes

**Comment by cropredyHelix** [comment]
Also fflib_queryFactory is unable to construct queries of PermissionSet for PermissionsXxxxx fields added since V37 like `PermissionsDeleteFieldHistory` which was added in V42.0 as file `fflib_SObjectDescribe.cls-meta.xml` is at v37.0

**Comment by afawcett** [comment]
Done
