### ISSUE TITLE
fflib_SObjectDomain and newMap on triggerHandler()

### ISSUE THREAD

**Issue by lonnieleecomer** [apex-enterprise-patterns/fflib-apex-common#228]
I don't understand why the Trigger.newMap hasn't been exposed using the triggerHandler method? This is very useful in many instances. Can someone explain why it isn't in there? Seems like the easiest fix ever for lacking functionality.

**Comment by cropredyHelix** [comment]
and why doesn't the `RecordsById` arg passed to onBeforeUpdate, etc suffice?

**Comment by daveespo** [comment]
Agreed with @cropredyHelix  -- it seems like `RecordsById` is what you want

The native `Trigger` property accessors can't be mocked in unit tests
