### ISSUE TITLE
fflib_QueryFactory().selectFieldSet() fails with when FieldSet queries namespaced fields

### ISSUE THREAD

**Issue by rsoesemann** [apex-enterprise-patterns/fflib-apex-common#24]
I have a valid FieldSet that contains field of a managed Custom Object and some fields of a related objects

When I run this code in unmanaged namespace-less org 

```
new fflib_QueryFactory(CustomObject__c.SObjectType)
            .selectFieldSet(SObjectType.CustomObject__c.Fieldsets.MyFieldSet)
```

it perfectly works. When try the same in a managed org with namespace (make Cusom Object and the related Object part of this namespace) it fails with:

```
caused by: UP2GO_2F.fflib_QueryFactory.InvalidFieldException: Invalid field 'NAMESPACE__Field__c' for object 'NAMESPACE__CustomObject__c'

Class.NAMESPACE.fflib_QueryFactory.getFieldToken: line 95, column 1
Class.NAMESPACE.fflib_QueryFactory.selectFieldSet: line 276, column 1
Class.NAMESPACE.fflib_QueryFactory.selectFieldSet: line 262, column 1
Class.NAMESPACE.MasterPartSelectCtrlExt: line 94, column 1
```

**Comment by afawcett** [comment]
Hi @up2go-rsoesemann is there still an issue here? @capeterson whats your thoughts?

**Comment by capeterson** [comment]
If it's still an issue certainly needs to be fixed, I also need to reconcile the private and public versions, I think we've had a few bug fixes on the internal version I need to migrate to this repo.

**Comment by daveespo** [comment]
Old and possibly fixed?
