### ISSUE TITLE
Query Selector cant select FieldDefintiion QualifiedAPI Name for custom metadata selector

### ISSUE THREAD

**Issue by pranayjswl007** [apex-enterprise-patterns/fflib-apex-common#240]
It looks like the selector pattern is not compatible with Entity Definition and Field Definition
Code:

Code:

  ```
flib_QueryFactory queryFactory = newQueryFactory();
  queryFactory = queryFactory.selectField('FieldName__c.QualifiedApiName');

```

Exception: 
```
Error on line 119, column 1: fflib_QueryFactory.NonReferenceFieldException: OmniPriority__mdt.FieldName__r is not a lookup or master-detail field but is used in a cross-object query field.
Class.fflib_QueryFactory.getFieldPath: line 119, column 1
Class.fflib_QueryFactory.selectField: line 207, column 1
Class.OmniPrioritySelector: line 28, column 1
AnonymousBlock: line 1, column 1
```

**Comment by ImJohnMDaniel** [comment]
Have you tried updating the fflib_QueryFactory__c API version to 47.0?

**Comment by kamell** [comment]
Hi @pranayjswl007, were you able to solve the issue? I am having this problem as well. Thanks!

**Comment by joeythomaschaske** [comment]
Related to https://github.com/apex-enterprise-patterns/fflib-apex-common/issues/208

**Comment by daveespo** [comment]
This sounds like the same thing as #208 -- I'm going to go ask for a repro case over there and close this as a duplicate
