### ISSUE TITLE
Dreamforce 2019?

### ISSUE THREAD

**Issue by dmchaplin** [apex-enterprise-patterns/fflib-apex-common#241]
Are there any Dreamforce sessions this year?

Is there a better place to ask these questions there here?  Maybe a success group?

**Comment by afawcett** [comment]
@dmchaplin i am not aware of any coverage in 2019, but @ImJohnMDaniel might know. Meanwhile please feel free to ask questions here, GitHub has a few more focused features for discussing open source projects. We can tag issues as discussions via labels.

**Comment by ImJohnMDaniel** [comment]
@dmchaplin -- There were no Dreamforce sessions about Apex Commons this year.
