### ISSUE TITLE
Discussion: Community Ownership

### ISSUE THREAD

**Issue by JAertgeerts** [apex-enterprise-patterns/fflib-apex-common#243]
There doesn't seem to be any active ownership anymore from the FinancialForce team. 
Is there an opportunity to open up the ownership to the community?

If not, our company is an extensive user and we're open to fork it to establish our own base for further developments to the framework.

Preferably, I'd like to keep it within the same repo as a lot of trailhead modules and other documentation points to these repos.

**Comment by JAertgeerts** [comment]
@sfryffdc @pwrightffdc @stephenwillcock  - if any of you are coming to dreamforce, I'd love to have a chat about the above.

**Comment by stephenwillcock** [comment]
It's great to hear that you find real value in the project.
Don't fork just yet though...
https://twitter.com/andyinthecloud/status/1178058904061612032

**Comment by JAertgeerts** [comment]
Seeing how this has been moved to a different repo - I think we're on track! Our company would love to help manage the workload - either myself or @wimvelzeboer can drive contributions and help the project move forward.

Let me know if you'd like to have a discussion prior to that @afawcett
