### ISSUE TITLE
fflib_SObjectDomain.getChangedRecords line 289 and 309, the changed record was added multiple times when this record has multiple fields changed

### ISSUE THREAD

**Issue by garychenming** [apex-enterprise-patterns/fflib-apex-common#254]
When a record has multiple fields changed, the two getChangedRecords method add it multiple times to changedRecords list.
I think it would be better to add a break statement after adding for line 289 and 309.

**Comment by wimvelzeboer** [comment]
I think this issue can be closed now, as its n[ow implemented](https://github.com/apex-enterprise-patterns/fflib-apex-common/blob/8b2a6f86f7f6c2e10d69ab3df0a5bbbac8c5e27b/fflib/src/classes/fflib_SObjectDomain.cls#L350)

**Comment by garychenming** [comment]
Yes, thanks.
