### ISSUE TITLE
Reducing SOQL's shared by services

### ISSUE THREAD

**Issue by konradbeck-creditech** [apex-enterprise-patterns/fflib-apex-common#287]
Is there a good way to reduce the number of queries when multiple service methods use the same selector?

**Comment by ImJohnMDaniel** [comment]
@konradbeck-creditech, I am not certain that I understand what you are asking.  Can you elaborate and provide some examples please?

**Comment by afawcett** [comment]
@konradbeck-creditech from a design perspective this sounds like a compound service scenario - thus move the queries into the compound service and pass the data sets into the child service as arguments (overloaded methods if you have existing client/caller code using them directly).

**Comment by SWhalen-gh** [comment]
an ability to cache data in a Selector or Service would be convenient, although overuse might be evidence of an anti-pattern somewhere in the code.
