### ISSUE TITLE
error while creating tasks for queues

### ISSUE THREAD

**Issue by marco10507** [apex-enterprise-patterns/fflib-apex-common#293]
I can assign a task to a queue and insert the task if I do it via the "Anonymous apex"; however, if I run the same code via a batch then it throws the following error message:

`System.DmlException: Insert failed. First exception on row 0; first error: FIELD_INTEGRITY_EXCEPTION, Assigned To ID: id value of incorrect type: 00G1l000002utScEAI: [OwnerId]`

The code I am running:

```
    fflib_ISObjectUnitOfWork uow = Application.uow.newInstance();

    Group queue = [SELECT Id, Name FROM Group WHERE Type = 'Queue' AND Name = 'my Queue' LIMIT 1];
    
    Task task = new Task(
            Subject = 'Test task',
            Priority = 'Hoog',
            Status = 'Niet gestart',
            WhoId = '0038E00001C80eEQAR',
            OwnerId = queue.Id,
            Description = 'Do something'
    );
    
    uow.registerNew(task);
    
    uow.commitWork();
```

**Comment by stohn777** [comment]
As long as unit tests are passing for Commons, AT4DX and their Samples (which I'd expect to be the case), I'm in support of the change.

**Comment by daveespo** [comment]
Per the comment on #294, all classes were updated to API 51
