### ISSUE TITLE
Who is using FFLIB in production?

### ISSUE THREAD

**Issue by mobilizer** [apex-enterprise-patterns/fflib-apex-common#297]
**Is there a list of reference customers who are using FFLIB in production?** 

I would suggest adding references to a wiki page. We are currently facing this question from business side before refactoring our existing org with FFLIB.

**Anybody using FFLIB in production?**
How big is the Org?
How many Devevelopers?
How big is the company you are using FFLIB for?

If I missed a website with this information: Please link it. Thanks!

**Comment by daveespo** [comment]
While I can see why you're asking this question, I don't think it's customary for closed-source projects to disclose the third party libraries that their applications depend on. Additionally, getting permission to use their brand/logo on a page maintained by a volunteer team of maintainers is time not spent on maintaining the library. In short, I don't think this is a reasonable request.

You can infer who is using the library based on who asks questions here in these GH repositories and who has posted about using the Enterprise Patterns in various Chatter groups / Stack Exchange postings, etc. 

It's no secret that the FF in FFLIB comes from FinancialForce and while they may not be directly depending on the open source fork of the patterns today, they have and still do contribute code so it's a good bet they've adopted the patterns.

**Comment by mobilizer** [comment]
Hey  @daveespo , the question was not about disclosing any secrets. 

I was just asking because there might be companies who are happy to tell in public that they are using FFLIB and are happy with it. 
Many companies  give references in public for commercial products/services. Why no strengthen a community project which you use.
