### ISSUE TITLE
Components cannot be deployed due to unit test issues

### ISSUE THREAD

**Issue by lopezfra** [apex-enterprise-patterns/fflib-apex-common#299]
hey, I am trying to deploy all the components into a new org and I am facing the following issues. 

<img width="1088" alt="Screen Shot 2020-09-28 at 18 52 05" src="https://user-images.githubusercontent.com/14021437/94549644-d2138300-0252-11eb-89bd-6c073ad5351e.png">

At the same time, and in order to do a double check I created a new developer environment, and this case the unit test issues are not there but there is a coverage issue in the same classes. 

<img width="1125" alt="Screen Shot 2020-09-29 at 12 54 56" src="https://user-images.githubusercontent.com/14021437/94549769-00915e00-0253-11eb-8abe-e3d4f39ac493.png">

This is the sdfx command I am using to deploy the components:

`sfdx force:source:deploy -p "libs/fflib" -l RunSpecifiedTests -r fflib_ApplicationTest,fflib_QueryFactoryTest,fflib_SecurityUtilsTest,fflib_SObjectDescribeTest,fflib_SObjectDomainTest,fflib_SObjectSelectorTest,fflib_SObjectUnitOfWorkTest,fflib_StringBuilderTest,fflib_SObjectMocks
`

Do you have any idea? Platform Encryption (shield) is not activated in this org. I am using components from Master branch.

Thanks

**Comment by ImJohnMDaniel** [comment]
@lopezfra, Thanks for open this issue report.  As we discussed on the apex-enterprise-patterns/fflib-apex-mocks#100, we ran a quick test on the master branch of fflib-apex-mocks and fflib-apex-commons projects.  The consensus is that cause of this failure must be environmental.  

Are there any process builders, flows, or custom trigger logic on the Opportunity SObject that would adjust the Opportunity name value at all?

**Comment by lopezfra** [comment]
@ImJohnMDaniel thanks for your quick response!. Really I don't understand what is happening. The first scenario with the unit test exceptions is clear, the failure is environmental. However, I am concern the second one, related to the coverage issue...I just created a new developer org (empty) and exactly the same result, test coverage issue. Maybe the problem is because I am not executing all the required unit tests during the deployment? Following the sfdx command I am using:

sfdx force:source:deploy -p "libs/fflib" -l RunSpecifiedTests -r fflib_ApplicationTest,fflib_QueryFactoryTest,fflib_SecurityUtilsTest,fflib_SObjectDescribeTest,fflib_SObjectDomainTest,fflib_SObjectSelectorTest,fflib_SObjectUnitOfWorkTest,fflib_StringBuilderTest,fflib_SObjectMocks

**Comment by ImJohnMDaniel** [comment]
regarding the code coverage issue...  does the `libs/fflib` folder have all of the codebase or simply just the pieces of the framework that you are using?

Also, can you try the deployment again with `--testlevel RunLocalTests` flag, please?

**Comment by lopezfra** [comment]
mmmm, interesting, now the number of apexTestMethods is more than before and the deployment is succeeded. It seems I didn't add all the required unit tests to my sdfx command....I added only those with the apex class name suffix 'Test' but probably there are more inside the rest of the apex classes...and using RunLocalTests all of them are executed.

Thank you so much! I am going to try to find now the environmental failure in the another org, 👍 Keep you updated

**Comment by ImJohnMDaniel** [comment]
Yup, this makes sense.

We have known that the UOW and base selector class are low on code coverage but deployments of all of the framework and running all of the unit tests is the workaround.  When you specify a deployment and specify only a few unit tests, then each of the classes affected by the unit test each have to have 75% coverage individually.  When you run all local tests, the requirement appears to rely on the whole org coverage as the gate and not the coverage of the individual classes as the gate.

We will be fixing the individual code coverage of those classes in the near future but for now `RunLocalTests` is your workaround.

Let me know if you have questions.

**Comment by lopezfra** [comment]
yeah! agree, I will check first the environmental issue (not clear the reason yet) and after that I will go ahead with this workaround...Thanks again for your effort and quick responses!

If I have some free time I will increase the coverage of those classes and create a PR to this repo.
