### ISSUE TITLE
Why does the FFLIB framework enforce CRUD security and sharing rules by default for Domains?

### ISSUE THREAD

**Issue by 1903Daniel** [apex-enterprise-patterns/fflib-apex-common#307]
Dear community,

in FFLIB, a Domain enforces CRUD security and sharing rules by default. We use FFLIB Domains for implementing triggers. In the Salesforce standard, triggers run in system context, meaning they don't enforce CRUD security, and don't enforce sharing rules if "with sharing" is omitted from the class declaration. In almost every use case, we want to keep the Salesforce standard behaviour. For that, we reflected on the fact that triggers are fix business processes running in the background. They should run through regardless of what permissions the current user has. In addition, the user is often not even aware of these processes, so a trigger run that fails due to missing permissions would lead to an error message quite confusing to the user. So we are considering to patch fflib_SObjectDomain in our org to not enforce the permissions by default.

Our discussion lead us to the question: why does the FFLIB framework enforce CRUD security and sharing rules by default for Domains?

Your answer is highly appreciated and helps us, and the community, to better understand the security implications of the framework.

Best regards,

Daniel Wutz

**Comment by wimvelzeboer** [comment]
Hi @1903Daniel 

You can use the Configuration in the domain to disable the CRUD security. Like in this example where its had been added to the domain constructor

`
public without sharing Cases extends fflib_SObjectDomain 
{
    public Cases()
    {
        Configuration.disableTriggerCRUDSecurity();
    }
    .....
}
`

**Comment by 1903Daniel** [comment]
@wimvelzeboer Thank you for the suggestion. I already had something like this in mind. The question was rather around the purpose of the default settings.

On Stackexchange, an approach was suggested that I like even better: https://salesforce.stackexchange.com/a/328780/90791

**Comment by daveespo** [comment]
I agree that the default is inconsistent/inconvenient from what you'd expect.

Unfortunately it would be impossible to change the default given that it would break/change expected behavior so the best solution is the one proposed in the stackexchange article
