### ISSUE TITLE
Querying Campaign causes "Permission to access an Campaign denied."

### ISSUE THREAD

**Issue by adayIvey** [apex-enterprise-patterns/fflib-apex-common#321]
I am not sure why but then I try to query the Campaign object using fflib I get "Permission to access an Campaign denied."
but when I just do it with a regular SOQL Query it works fine.

`public class TempTester extends fflib_SObjectSelector
{

    public List<Schema.SObjectField> sObjectFieldList;
    
    public TempTester() 
    {
        sObjectFieldList = new List<Schema.SObjectField>
        {
        	Campaign.Id
  		};
    }
    
    public List<Schema.SObjectField> getSObjectFieldList() 
    {
        return sObjectFieldList;
    }

    public Schema.SObjectType getSObjectType() 
    {
        return Campaign.sObjectType;
    }

	public List<Campaign> SelectByStatus1(string status) 
    {

        return [SELECT Id, Status, Name FROM Campaign WHERE Status = 'Open'];
    }
    
    public List<Campaign> SelectByStatus2(string status) 
    {
       
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Status =: status');
        
        return (List<Campaign>) Database.query(query.toSOQL());
        
    }
    
}

@IsTest
public class TempTester_Test 
{

    @IsTest
    static void Test_SelectByStatus1()
    {
        
        test.startTest();
        
        User runAS = [SELECT Id, Name FROM User WHERE Name = 'Test Participant2'];
        
        System.runAs(runAS) 
        {
            TempTester tempTester = new TempTester();
			List<Campaign> campaigns = tempTester.SelectByStatus1('Open');
        
        	system.assert(campaigns.size() >= 1);
        }
        
        test.stopTest();
        
    }

    
    @IsTest
    static void Test_SelectByStatus2()
    {
        test.startTest();
        
        User runAS = [SELECT Id, Name FROM User WHERE Name = 'Test Participant2'];
        
        System.runAs(runAS) 
        {
            TempTester tempTester = new TempTester();
			List<Campaign> campaigns = tempTester.SelectByStatus2('Open');
        
        	system.assert(campaigns.size() >= 1);
        }
        
        test.stopTest();
    }

    
    @testSetup 
    static void setup() 
    {
        
        PMITestData.BuildTestData();
        
    }
    
}
`

The user I am running the query's as is member of a community profile
I am not sure why the SOQL query works fine but fflib gives the perms error

**Comment by daveespo** [comment]
Community Users don't have access to Campaign -- they need to be Salesforce licensed users and possibly also have the marketing perm turned on. Selectors enforce CRUD by default whereas your loose SOQL in the test method (SelectByStatus1) is running in system mode.
