### ISSUE TITLE
How to handle growing number of loops

### ISSUE THREAD

**Issue by reignman5** [apex-enterprise-patterns/fflib-apex-common#335]
Hi,

lets imagine I have a domain class with 10 different methods I want to call from the onBeforeInsert method.
My problem now is that with every new method Im adding to the onBeforeInsert method, I am also creating a new for loop.
Because as I learned every method should just do one thing.

Is this gonna be problematic in the future regarding perfomance?
Are you handling it differently?

**Comment by daveespo** [comment]
@wimvelzeboer  gave some guidance on this topic over on #332
