### ISSUE TITLE
Dividing an App into Separation of Concern layers

### ISSUE THREAD

**Issue by PseudoDarwinist** [apex-enterprise-patterns/fflib-apex-common#338]
So I have to build a new lightning app, or thats what i want to begin with.I need to create three webforms(Sites and Visualforce Pages).1st webform will allow customers to fill their data, personal details and travel details like destination they are travelling to, based on which we are making a callout to third party and showing some mandatory details on the webform.Customers are mandated to upload some mandatory attachments(without password locked) on the form.Once the webform is submitted, it creates a Case in the org with all the details filled by customers and all the attachments as Files.Now inside the Org, Once the case is created, i need to create some LWC components, which will also make some callouts and show some data on the component.Once the Case is closed,We need to callout to other integration to update the data as well.This is the rough sketch i want to paint.Can somebody help me how i can apply separation of Concern here and divide the code into layers so that i don't mess it up to start with.

**Comment by ImJohnMDaniel** [comment]
G'day @PseudoDarwinist 

Certainly the diagram mentioned [here](https://trailhead.salesforce.com/en/content/learn/modules/apex_patterns_sl/apex_patterns_sl_learn_sl_principles) showing the various service tier clients helps to frame this answer.

The LWCs and supporting controllers would be in the Service Tier client layer.  They would, in turn, rely on Service classes to perform operations.  The service tier would offload to domain or integration layer classes as needed.

I would also suggest you read the book -- [Salesforce Lightning Platform Enterprise Architecture](https://www.amazon.com/Salesforce-Lightning-Platform-Enterprise-Architecture-ebook/dp/B07SYJBV7P/ref=sr_1_3) -- as it goes into much greater depth on this subject.
