### ISSUE TITLE
Illegal assignment from fflib_Domain to fflib_ISObjectDomain

### ISSUE THREAD

**Issue by cropredyHelix** [apex-enterprise-patterns/fflib-apex-common#346]
Documenting this for others who may have updated their apex-commons onto an existing code base where the existing code base is older than https://github.com/apex-enterprise-patterns/fflib-apex-common/pull/300 (_Add new Domain Structure_)

If you have:

    fflib_ISObjectDomain domain =  Application.Domain.newInstance(sObjIds);	// construct domain class for Ids of sobjType X

You need:

    fflib_ISObjectDomain domain = (fflib_ISObjectDomain) Application.Domain.newInstance(sObjIds);	// construct domain class for Ids of sobjType X

This pattern arises from the example in:

- Salesforce Lightning Platform Enterprise Architecture 3rd Edition 
- Chapter 6 Application Domain Layer 
- Step 8 Implementing a Generic Service

**Comment by wimvelzeboer** [comment]
@cropredyHelix This is indeed the case, as the domain interface structure has a different root. Therefore the return type of the Domain factory is no longer fflib_ISObjectDomain but fflib_IDomain. 

The Interface structure is now:
fflib_IDomain -> fflib_IObjects -> fflib_ISObjects -> fflib_ISObjectDomain

**Comment by cropredyHelix** [comment]
@wimvelzeboer 
right-o, I could see that in the new code. I created the Issue as documentation/troubleshooting for other fflib users who might encounter this issue once installing the latest apex-commons.  I'm not expecting you to make any changes in apex-common.

**Comment by daveespo** [comment]
Thanks for the update Eric and thanks to William for the confirmation. I'll close this ticket now and hope others can find it with little effort
