### ISSUE TITLE
Ambiguous method signature: void setMock(MyDomainClass)

### ISSUE THREAD

**Issue by cropredyHelix** [apex-enterprise-patterns/fflib-apex-common#347]
Documenting this for others who may have updated their apex-commons onto an existing code base where the existing code base is older than https://github.com/apex-enterprise-patterns/fflib-apex-common/pull/300 (_Add new Domain Structure_)

@wimvelzeboer 

_Typical usage is with apexmocks_

if you have in your test class (assuming `Assets` is your domain class that implements `fflib_ISObjectDomain`)

    // Given mock Assets domain
    Assets mockAssetsDomain = (Assets) mocks.mock(Assets.class);
    mocks.startStubbing();
    mocks.when(mockAssetsDomain.sObjectType()).thenReturn(Asset.SObjectType);
    mocks.stopStubbing();

    // Given mock domain injected
    Application.Domain.setMock(mockAssetsDomain);   // <<== generates Ambiguous method signature: void setMock

This happens because the inner class fflib_Application.DomainFactory has these two methods:

    protected virtual void setMock(fflib_ISObjectDomain mockDomain) {
       mockDomainByObject.put((Object) mockDomain.sObjectType(), (fflib_IDomain) mockDomain);
    }

and 

    protected virtual void setMock(fflib_IDomain mockDomain) {
	mockDomainByObject.put(mockDomain.getType(), mockDomain);
    }

but because your legacy domain class implements `fflib_ISObjectDomain` which extends `fflib_IDomain`, the compiler can't tell which of the two `setMock`s to use.

You can resolve this by changing  

    // Given mock domain injected
    Application.Domain.setMock(mockAssetsDomain);   // <<== generates Ambiguous method signature: void setMock

to (note casting):

    // Given mock domain injected
    Application.Domain.setMock((fflib_ISObjectDomain) mockAssetsDomain);

**Comment by daveespo** [comment]
Again, thanks Eric for the clear repro case and solution.
