### ISSUE TITLE
Interactor Class? (Discussion)

### ISSUE THREAD

**Issue by nhall97** [apex-enterprise-patterns/fflib-apex-common#354]
Is there space for the interactors principle within the world of Salesforce?

Uncle Bob: https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html
Blog with examples: https://fullstackmark.com/post/11/better-software-design-with-clean-architecture

The point being that leaky controllers do not always help us keep track of database inserts etc. The space I see this fulfilling is the space of a Selector, but for database interactions such as write/delete/update etc.

Perhaps there is a better space for this discussion, but thought it would be good to start here.

Nathan

**Comment by daveespo** [comment]
Closing due to the age of this issue. We now have a Discussions tab in this repo if you'd like to restart this discussion and provide some concrete examples of what you're proposing.
