### ISSUE TITLE
Would you have one Selector of a particular object for your entire Org, or would you create one per App/Process/Functionality in a Mono Repo Project

### ISSUE THREAD

**Issue by AllanOricil** [apex-enterprise-patterns/fflib-apex-common#373]
Would you have one Selector of a particular object for your entire Org, or would you create one per App/Process/Functionality?

At the moment we are creating one seletor per object and I dont really think this is the best way of using fflib because we would endup with different apps/process/functionality being tightly coupled with that one particular selector. 
My view is that even if we are not creating an app or functionality that will endeup being a managed package, we should always decouple its classes and Metadata. The reason for that is to make it easy to remove it entirely  in case we don't need it anymore. If we put everything on a single Selector, later we will have to edit that Selector just to be able to remove the app/functionality/process.
But doing this way we will kind have code repetition, because one app might use the same data, fields and access level that the other app is using. But this repetition can be treated using Inheritance. We  could have one common Selector, and each app would have its own Selector extending that common one. But because this not documented, I would like to confirm that this is a good idea. 

I'm asking it because I noticed that a particular functionality that I created could be turned into a fflib app, even if I'm not going to turn it a managed/unlocked package. It looks really cleaner to have all of its resources (selectors, domains, trigger handlers, application, controllers) in its own separate app and folder, rather than having a big common Application (fflib application class).  It makes everything so easy to find and delete the entire functionality in case we don't need it anymore. 

This is the way Im thinking about using fflib when working in a Mono Repo Project

![image](https://user-images.githubusercontent.com/55927613/137777801-69e060e3-d057-431a-88f0-239b78f8e561.png)

So what do you think?

**Comment by ImJohnMDaniel** [comment]
Well, it is important to remember that the Selector Pattern does not call for a selector class to always have every field on an SObject.  Instead, the Selector Pattern defines what the minimum constitution should be for a SObject record.  It forms the basis of the contract "for what the SObject record should be guaranteed having queried".  It does not specify the contract that "every field will be queried."

Your reference is definitely one of those reasons to not specify all fields.  There is a maximum length to a SOQL query and specifying every field on large objects could easily run into that limit.  Another reason not to specify all fields on the Selector is the overhead involved with Long Text Area and Rich Text Area fields.  Those fields incur a lot over memory overhead when most of the time, those fields are not required in the transaction.  Better to use the query factory's "selectField" method to add them to the minimal contract of fields when needed at the selector method level.

The other issue with multiple selectors is that you lose out on the benefit of a single point of reference and a single point of maintenance by specifying more than one selector.  In multi-selector scenarios, your selector-clients need to be more intimately aware of which selector they need for which purpose.   If you have multiple selectors, then you need to manually keep them consistent with the same "minimal contract of fields."  In large organizations, many different processes could interact with the SObject records.  Having them originate from one of many sources runs the greater risk of encountering SObjectField Exceptions where the field is referenced but not first queried.

The last concern that I can think of is that the Application Factory can't uniquely identify the selector to use for an Sobject.  This is, of course, assuming that you are using an Application Factory for the Selectors.  I highly recommend doing so as it sets the codebase up perfectly to swap in ApexMocks where ever needed and promotes a more loosely coupled codebase.

The prescriptive advice on this question definitely has been "one selector per SObject" and, while you need to be mindful of the topics mentioned above, it has definitely been a pattern that has proven success in countless implementations.

**Comment by AllanOricil** [comment]
@ImJohnMDaniel  I still think that one selector per application brings so many benefits and no cons for a Mono Repo Project. (consider it one that does not use packages and many sfdx projects, because we can't not because we don't want)

PROS:
1 - I can easily see which fields that particular app uses, declaring a getSObjectFieldList() with all fields that a particular APP may care about. It does not mean Im going to use all of them on every Selector method, it is just there so a developer can quickly see which fields matter to the App. This can also be used to guide the developer to create a permission set and put only those that the APP care for that Object.
2 - I can remove the Entire App resources knowing I would not damage any other App (decoupled apps). If App A and B use the same Selector, and I need to remove App B, I will have to edit the Selector to remove methods or fields that App B was using, just to clean things.
3 - Developers will not Accidentally remove a method or a field reference from getSObjectFieldList() wich would then impact a method that is using "newQueryFactory(true)". Like, imagine both App A and B use the same method, and both use newQueryFactory(true). Now Imagine someone accidentally removed one field that App B needed. This situation will not throw an exception unless someone test App B or it was covered on an Apex Test. And you know not everyone or organization spends time writting good tests. So this may happen in case we use a Single Selector two Apps share.

CONS: 
I dont see any. You can list the ones you think and then we leave it here at the end so other people can take their own conclusions. 

And we can extend it to all the other resources of an Fflib Application (domains, trigger handlers, selectors, services).

**Comment by AllanOricil** [comment]
@ImJohnMDaniel  I will start studying this AT4DX. How can I get started with that? Do you have a video that would help me?
