### ISSUE TITLE
How do we Mock selectors that query Child Relationship?

### ISSUE THREAD

**Issue by AllanOricil** [apex-enterprise-patterns/fflib-apex-common#375]
Could you show how would you mock a Selector method that selects Accounts and its Contacts? 

Imagine that the method is called

`selectAccountsByIdWithContacts(Set<Id> accountIds);`

and it issues a query like the one below

`SELECT Id, Name, (SELECT Id, FirstName, LastName FROM Contacts) FROM Account WHERE Id IN :accountIds`

This method returns List<Accounts> and each account entry can access a list of Contacts called "Contacts".

Im asking it because I tried to mock another object with its children and I got this error message

`Field is not writeable: DocumentSigningRequest__c.DocumentSigningRequestSigners__r`

So I don't know how to mock this type of query.

**Comment by wimvelzeboer** [comment]
Ah yeah, mocking readonly fields in records, and related records is somewhat more difficult todo.
But luckily the architect behind the framework @afawcett came up with a solution; [Mock Sub-Selects](https://gist.github.com/afawcett/8dbfc0e1d8c43c982881)
