### ISSUE TITLE
Can I use a Selector in a controller method directly, or is it required to call a Service that is going to call the selector?

### ISSUE THREAD

**Issue by AllanOricil** [apex-enterprise-patterns/fflib-apex-common#379]
Can I use a Selector in a controller method directly, or is it required to call a Service that is going to call the selector?
Is there a technical problem? or is it just a recommendation to respect "SoC"?
I fell that creating a service method just to call a selector disrespects "KISS".
So what the maintainers think about it?

Let me give an example. Currently I have this controller method which just calls a Selector

````java
@AuraEnabled
    public static List<ContentDocumentLink> fetchContentDocumentLinks(Id linkedEntityId) {
        try {
            return DSP_ContentDocumentLinksSelector.newInstance()
                .selectAllInLinkedEntityIds(new Set<Id>{ linkedEntityId });
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
````

Now, according to "SoC" I actually "must" call a service class that will call the selector. By doing so, I will end up with these additional classes and interface, just to accomplish the same thing:

1 - DSP_ContentDocumentLinksService
2 - DSP_ContentDocumentLinksServiceImpl
3 - DSP_IContentDocumentLinks

I had to write a lot more :/

**Comment by cropredyHelix** [comment]
@AllanOricil 

shouldn't this line:

    List<Accounts> accounts = AccountsSelector.newInstace().selectAccountsWithNamesOfHotUsaAccounts(accountsIds);

be?

    List<Account> accounts = AccountsSelector.newInstance().selectAccountsWithNamesOfHotUsaAccounts(accountsIds);

that is, the selector returns a list of SObjects, not a list of domains

**Comment by AllanOricil** [comment]
Yes, you are right.
