### ISSUE TITLE
Deploying to production is failing

### ISSUE THREAD

**Issue by MattHCarrier** [apex-enterprise-patterns/fflib-apex-common#425]
**Describe the bug**
When deploying fflib_common to production a test is failing and I am receiving the following error:

method: fflib_SObjectUnitOfWorkTest.testDerivedUnitOfWork_CommitDMLFail -- System.AssertException: Assertion Failed: Exception message was stack Class.fflib_SObjectUnitOfWorkTest.testDerivedUnitOfWork_CommitDMLFail: line 339, column 1

seems like System.DMLException is throwing a stack trace instead of the expected "REQUIRED_FIELD_MISSING" error.

apex mocks installed no problem and I have installed both mocks and commons in multiple scratch/sandbox environments no problem.

**Comment by MattHCarrier** [comment]
Issue had to do with most of the test scenarios revolve around inserting opportunities. I had custom validation included on the opportunity which was throwing a different message than what was expected in the assertion.

**Comment by ImJohnMDaniel** [comment]
G'day @MattHCarrier.  I am glad to hear that you were able to determine the root cause on this issue.  Cheers!
