### ISSUE TITLE
fflib_SObjectSelector and fflib_SObjectUnitOfWork have insufficient test code coverage.

### ISSUE THREAD

**Issue by matthewpomar-at-ndr** [apex-enterprise-patterns/fflib-apex-common#473]
**Describe the bug**
fflib_SObjectSelector and fflib_SObjectUnitOfWork have insufficient test code coverage. When deploying Apex Common to an org, the deploy fails with following errors:

> Code Coverage Failure
> Your code coverage is 73%. You need at least 75% coverage to complete this deployment.
> fflib_SObjectSelector
> Your code coverage is 74%. You need at least 75% coverage to complete this deployment.
> fflib_SObjectUnitOfWork

**To Reproduce**

1. Install fflib ApexMocks and Apex Common to dev org.
2. Deploy the classes using DevOps tool of choice, running all tests (or tests included with fflib libraries).
3. See error above.

**Expected behavior**
fflib libraries should have sufficient test code coverage.

**Screenshots and text of error observed**

<img width="582" alt="image" src="https://github.com/apex-enterprise-patterns/fflib-apex-common/assets/138714531/0c2fabdb-6877-4183-b79d-37b1c4073ba2">

**Version**
Latest version as of 12/5/2023.

**Comment by ImJohnMDaniel** [comment]
G'day @matthewpomar-at-ndr.  Thanks for reaching out.

The ApexMocks and Apex Common frameworks each have more than sufficient code coverage to be deployed to a production environment.

Are you, by chance, trying to deploy only certain files instead of the complete framework?
