### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by adayIvey** [apex-enterprise-patterns/fflib-apex-common#485]
How do I know what version of fflib I have installed in my org vs what is the current version, I see no concept of release versioning for this Library.

**Comment by ImJohnMDaniel** [comment]
G'day @adayIvey 

FFLIB (or any of the AEP repos) does not offer any concept of versioning beyond the inherent versioning of the GIT commit history.  This allows teams like yours to create their own versions that make sense in your situation.

Ideally, your team maintains a private clone of this repo which you use for your application deployments.  You can fetch any changes from the main repo here whenever you wish and then deploy those changes to your environment.  If your environment is already in sync with the latest changes, the deployment would be essentially a "non-event".
