### ISSUE TITLE
Add helper methods to fflib_SObjectDomain for changed fields

### ISSUE THREAD

**Issue by dhoechst** [apex-enterprise-patterns/fflib-apex-common#52]
A common need in triggers is to identify whether a field or set of fields has been changed. I like the model that is used in the [TriggerX](https://github.com/se6wagner/TriggerX/blob/master/TriggerX/src/classes/TriggerX.cls#L130) framework to pass in a list of Strings or a list of sObjectFields. I'd also add a way to pass in a field set to see if any fields in the field set have changed.

**Comment by MayTheSForceBeWithYou** [comment]
@dhoechst @afawcett 
https://github.com/financialforcedev/fflib-apex-common/pull/87

**Comment by afawcett** [comment]
Thanks will take a look soon! :+1:

**Comment by afawcett** [comment]
@MayTheSForceBeWithYou  This looks good, though the PR is currently in conflict, if you can sort, happy to merge. :+1:

**Comment by daveespo** [comment]
Resolved with #87
