### ISSUE TITLE
Unable to deploy: no "System Administrator" or "Read Only" profiles

### ISSUE THREAD

**Issue by matrix818181** [apex-enterprise-patterns/fflib-apex-common#78]
I get the following message when I try to deploy on my production environment. It's weird because I was able to deploy the same package on my sandbox.

From what I can understand, the "unit test user" is not able to create new user for test.

Can somebody help me ? I really need to be able to install the package on my prod environment.

Thx

> Deployment CompleteTest failure, method: fflib_SecurityUtilsTest.readonly_field_access -- System.QueryException: List has no rows for assignment to SObject stack Class.fflib_SecurityUtilsTest.setupTestUser: line 38, column 1
> Class.fflib_SecurityUtilsTest.readonly_field_access: line 56, column 1
> 
> Test failure, method: fflib_SecurityUtilsTest.readonly_objectAndField_access -- System.QueryException: List has no rows for assignment to SObject stack Class.fflib_SecurityUtilsTest.setupTestUser: line 38, column 1
> Class.fflib_SecurityUtilsTest.readonly_objectAndField_access: line 153, column 1
> 
> Test failure, method: fflib_SecurityUtilsTest.readonly_object_access -- System.QueryException: List has no rows for assignment to SObject stack Class.fflib_SecurityUtilsTest.setupTestUser: line 38, column 1
> Class.fflib_SecurityUtilsTest.readonly_object_access: line 99, column 1
> 
> Test failure, method: fflib_SecurityUtilsTest.sysadmin_objectAndField_access -- System.QueryException: List has no rows for assignment to SObject stack Class.fflib_SecurityUtilsTest.setupTestUser: line 38, column 1
> Class.fflib_SecurityUtilsTest.sysadmin_objectAndField_access: line 238, column 1

**Comment by capeterson** [comment]
Are you by chance set to a non-English language as the user running the deployment? The issue seems to be that there are no profiles name "Read Only" or "System Administrator" available. 

Sadly there's no way to make references to these profiles without hard-coding the name, a gap I really, really wish Salesforce would fix. I did just get an interesting idea that might help us make this more portable if that is indeed the problem. Let me know?

**Comment by capeterson** [comment]
It seems my idea for a way to fine profiles regardless of user locale is viable. If you confirm that your issue is from running as a non-English user I'll get it implemented here soonish.

**Comment by afawcett** [comment]
@capeterson Assuming the answer is yes, are you able to contribute your idea?

**Comment by Aequitas737** [comment]
Also getting this issue when language is changed to Spanish, English users work fine.

**Comment by daveespo** [comment]
This seems like a bug but one without a viable solution given that there is no reliable way to identify Profiles except by their localized Name field
